download: download.cc
	g++ -std=c++11 -o download download.cc -pthread -lmuduo_base -lmuduo_net
download2: download2.cc
	g++ -std=c++11 -o download2 download2.cc -pthread -lmuduo_base -lmuduo_net
download3: download3.cc
	g++ -std=c++11 -o download3 download3.cc -pthread -lmuduo_base -lmuduo_net
