basic:
	g++ -std=c++11 -o server_basic server_basic.cc sudoku.cc -pthread -lmuduo_base -lmuduo_net

pool:
	g++ -std=c++11 -o server_pool server_threadpool.cc sudoku.cc -pthread -lmuduo_base -lmuduo_net
multiloop:
	g++ -std=c++11 -o server_multiloop server_multiloop.cc sudoku.cc -pthread -lmuduo_base -lmuduo_net
